name: Deploy to docker hub (v-tag)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  github:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: ghcr.io/darmiel/perplex-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
